services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - llm
    networks:
      - llm-net

  llm:
    image: ghcr.io/huggingface/text-generation-inference:1.4
    command: --model-id distilgpt2
    ports:
      - "5000:80"
    networks:
      - llm-net
    environment:
      TGI_ALLOW_ORIGIN: "*"



networks:
  llm-net:
    driver: bridge

