apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ook0301/llm-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "llm_db"
            - name: LLM_URL
              value: "http://llm:80/generate"

