apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ook0301/llm-backend:latest
          ports:
            - containerPort: 4000
          env:
              - name: POSTGRES_USER
                value: "postgres"
              - name: POSTGRES_PASSWORD
                value: "postgres"
              - name: POSTGRES_DB
                value: "llm_db"
              - name: POSTGRES_HOST
                value: "db"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000


