apiVersion: v1
kind: Pod
metadata:
  name: test-node
spec:
  containers:
    - name: test-node
      image: node:20-alpine
      command: ["sh", "-c"]
      args: 
        - |
          apk update && \
          apk add curl && \
          while true; do sleep 3600; done